#!/bin/sh
VERSION=1.0.0

usage()
{
    cat <<EOF
    battery

    USAGE
    battery                 Prints the current battery percentage.

    FLAGS
    --help, -h:        Display this help message and exit.
    --version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

output() {
  printf " %s  %s%% " "$1" "$2"
}

BATTERY_CAPACITY="$(cat /sys/class/power_supply/BAT0/capacity)"
BATTERY_STATUS="$(cat /sys/class/power_supply/BAT0/status)"

if [ "$BATTERY_STATUS" = "Charging" ] || [ "$BATTERY_STATUS" = "Full" ]; then
   printf " %s  %s%% "  "$BATTERY_CAPACITY"
   exit 0
fi

if [ "$BATTERY_CAPACITY" -gt 95 ]; then
   output   "$BATTERY_CAPACITY"
elif [ "$BATTERY_CAPACITY" -gt 75 ]; then
   output   "$BATTERY_CAPACITY"
elif [ "$BATTERY_CAPACITY" -gt 50 ]; then
   output   "$BATTERY_CAPACITY"
elif [ "$BATTERY_CAPACITY" -gt 25 ]; then
   output   "$BATTERY_CAPACITY"
elif [ "$BATTERY_CAPACITY" -gt 0 ]; then
   output   "$BATTERY_CAPACITY"
else
   output  "$BATTERY_CAPACITY"
fi
exit 0
