#!/bin/sh
VERSION=1.0.0

usage()
{
    cat <<EOF
    EASYTIME

    USAGE
    easytime                 Print out the time in an easy-to-read way.

    FLAGS
    --help, -h:        Display this help message and exit.
    --version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

date "+ %-l:%M %p " | tr -d '\n'
