#!/bin/sh
VERSION=1.0.0

usage()
{
    cat <<EOF
    FIND REPLACE

    USAGE
    fr "\$1" "\$2"     Find "\$1" and replace it with "\$2" recursively.

    FLAGS
    --help, -h:        Display this help message and exit.
    --version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

find "$PWD" -type f -not -path ".git/*" -not -path "node_modules/*" -not -path "target/*" -exec sed -i "s/$1/$2/g" {} \;
