#!/bin/sh
VERSION=1.0.0
NS_EDITOR="$(if [ -n "$EDITOR" ]; then printf "%s" "$EDITOR"; else printf "%s" "/usr/bin/nvim"; fi)"
NS_PATH="$HOME/github/joshuahoeflich/jde/scripts/src"

usage()
{
    cat <<END
NEW SCRIPT

USAGE
ns SCRIPTNAME      Create or modify the script titled SCRIPTNAME
                   in ~/.local/scripts/SCRIPTNAME

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

END
}

if [ -z "$1" ]; then
    printf "%s\n" "New script must have a name."
    usage
    exit 1
fi

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

if [ -f "$NS_PATH"/"$1" ]; then
    $NS_EDITOR "$NS_PATH"/"$1"
else
    cat << END > "$NS_PATH"/"$1"
#!/bin/sh
VERSION=1.0.0

usage()
{
    cat <<EOF
    <SCRIPTNAME_HERE>

    USAGE
    $1                 <DESCRIPTION HERE>

    FLAGS
    --help, -h:        Display this help message and exit.
    --version, -v:     Display the current version and exit.

EOF
}

case "\$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "\$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac
END
    $NS_EDITOR "$NS_PATH"/"$1"
fi

chmod +x "$NS_PATH"/"$1"
