#!/bin/sh
VERSION=1.0.0
NS_EDITOR="$(if [ -n "$EDITOR" ]; then printf "%s" "$EDITOR"; else printf "%s" "/usr/bin/nvim"; fi)"

usage()
{
    cat <<EOF
NEW SCRIPT

USAGE
ns SCRIPTNAME      Create or modify the script titled SCRIPTNAME
                   in ~/.local/scripts/SCRIPTNAME

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

EOF
}

if [ -z "$1" ]; then
    printf "%s\n" "New script must have a name."
    usage
    exit 1
fi

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

if [ -f ~/.local/scripts/"$1" ]; then
    $NS_EDITOR ~/.local/scripts/"$1"
else
    echo "#!/bin/sh" >> ~/.local/scripts/"$1"
    $NS_EDITOR ~/.local/scripts/"$1"
fi

chmod +x ~/.local/scripts/"$1"
