#!/bin/sh
VERSION=1.0.0

usage()
{
    cat <<EOF
POLYBLOCKS CONNECT

USAGE
pbc <section> <output> <id>   Put OUTPUT into SECTION within polyblocks. Note
                              that "id" defaults to 0 and is optional.

FLAGS
--help, -h:                   Display this help message and exit.
--version, -v:                Display the current version and exit.
EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

if ! command -v socat; then
  printf "%s\n\n" "FATAL: socat missing."
  printf "%s\n\n" "Please install socat to use this script."
  usage;
  exit 1;
fi

if [ -z "$1" ] || [ -z "$2" ]; then
  printf "%s\n\n" "FATAL: Section and input missing."
  printf "%s\n" "Please provide pbc with a section and input."
  usage;
  exit 1;
fi

BAR_ID="$(if [ -z "$3" ]; then 0; else "$3"; fi)"

printf "%s\n%s" "$1" "$2" | socat -t0 ABSTRACT-CONNECT:"$BAR_ID"_polyblocks_socket STDIN
