# Global is a special block; settings here change the entire output of the
# server. Right now, `separator` is the only config switch, but more could
# theoretically be added.
[global]
separator=" | "

# Define new sections of your status bar. Note that order matters; the blocks
# you define first will get printed first.
[battery]
script="/path/to/some/file"
interval=20

[weather]
script="/path/to/another/file"
interval=5
