# Global is a special block; settings here change the entire output of the
# server. Right now, `separator` is the only config switch, but more could
# theoretically be added.
[global]
separator=" | "

# Define new sections of your status bar. These will appear based on the
# *alphabetical order* of the section, so battery will come before weather.
[weather]
script="/path/to/another/file"
interval=5

[battery]
script="/path/to/some/file"
interval=20
